const brandNames = ['Bontrager', 'Trek'];
const productFamilies = [
  'Evoke',
  'Circuit',
  'Rhythm',
  'Troslo',
  'Trosla',
  'Aeolus',
  'Paradigm',
  'Line',
  'Kovee',
  'Flare',
  'Ion',
  'Transmitr',
  'Specter',
  'Blaze',
  'Charge',
  'Ballista',
  'Rally',
  'Velocis',
  'Quantum',
  'Starvos',
  'Solstice',
  'Little Dipper',
  'Big Dipper',
  'Remedy',
  'Madone',
  'Fuel EX',
];
const productLevels = [
  'R',
  'RT',
  'Pro',
  'XXX',
  'Comp',
  'Elite',
  'City',
  'Commuter',
  'WaveCel',
  'Road',
  'Mountain',
  'LTD',
  'MIPS',
  '3V',
  'TLR',
  'Boost',
];
const productTypes = [
  'Bike Helmet',
  'Bike Wheel',
  'Front Light',
  'Rear Light',
  'Light Set',
  'Cycling Gloves',
  'Bib Shorts',
  'Jersey',
  'Bike',
  'Rear Rack',
  'Bike Pump',
  'Cycling Glasses',
  'Premium Kickstand',
  'Leg Warmers',
  'Arm Warmers',
  'Baselayer',
  'Jacket',
  'Bike Computer',
];
const descriptions = [
  'This product is great.',
  'It\'s indeed a fine product.',
  'You should buy this product.',
  'Best-in-class.',
  'Sure you could buy another product, but this one is great!',
  'Why buy a different product when you could buy this one.',
];
const colorNames = [
  'Electric Yellow',
  'Cornflower Blue',
  'Black',
  'Vibrant Green',
  'Cyan',
  'Brown',
];
const colorFinishes = [
  'Gloss',
  'Matte',
  'Sparkle',
  '',
];
const sizes = [
  'X-Small',
  'Small',
  'Medium',
  'Extra-Medium',
  'Large',
  'X-Large',
  'XX-Large',
];

module.exports = {
  brandNames,
  productFamilies,
  productLevels,
  productTypes,
  descriptions,
  colorNames,
  colorFinishes,
  sizes,
};
